//! S047 — post-mint TributeDraft **full proof** (ownership + Merkle
//! inclusion), generated by the wallet and ZK-verified end-to-end.
//!
//! Where S046 proves the committed leaf folds into a committee-signed root
//! (Merkle + BLS cert, no ZK), this scenario exercises the **§4.2 full
//! circuit**: a single Honk proof that simultaneously establishes
//!
//!   * **ownership** — a Grumpkin signature by the TD's own key over the TD
//!     entity hash (`nft_hash`), bound to an L1 submitter + chain id; and
//!   * **inclusion** — a depth-32 Merkle path placing that `nft_hash` leaf
//!     under a committed root (re-derived and checked inside the circuit).
//!
//! Flow:
//!   1. Submit a real TributeDraft (S001's full happy path — real aggregation
//!      proof + on-chain submit). The submit emits `LeafInserted(treeId,
//!      leafIndex, leaf)`; `leaf` is the chain-folded TD `nft_hash`.
//!   2. Rebuild the **ownership half** from the SAME `td_header` + the TD body
//!      fields read back from `TributeDraft.getData`, and assert the witness's
//!      recomputed `nft_hash` equals the on-chain `leaf` (so the proof is over
//!      exactly what the chain committed).
//!   3. Build a self-consistent **inclusion half**: place `leaf` at its index in
//!      an empty depth-32 IMT and take the co-path + root (the `pso-protocol`
//!      Poseidon2 tree — the same one the node commits to). This needs no node
//!      finalization, so S047 runs wherever S001 does.
//!   4. `Wallet::prove_full(ownership, inclusion)` — generate the real proof.
//!   5. Verify it with the canonical `FullProof` circuit + barretenberg backend
//!      (the SAME verifier the chain's L1 path uses): the proof must verify, its
//!      four public inputs must be exactly `[owner, nft_hash, binding, root]`,
//!      and corrupting EITHER the ownership input (`owner`) OR the inclusion
//!      input (`expected_merkle_root`) must make verification fail — proving the
//!      single proof genuinely binds both halves.

use async_trait::async_trait;

use pso_chain_abi::addresses::TRIBUTE_DRAFT;
use pso_chain_abi::interfaces::ITributeDraft;
use pso_protocol::protocol::imt::Imt;
use pso_protocol::protocol::zk::ProofVerifier;
use pso_protocol::{Codec, PsoV1, Suite};
use pso_zk_backend::barretenberg::{Barretenberg, Proof};
use pso_zk_canonical::noir::full_proof::{FullProof, PublicInputs as FullPublicInputs};

use crate::scenarios::s001_happy_flow::submit_full_tribute_draft;
use crate::scenarios::s046_cert_inclusion::leaf_inserted;
use crate::{Scenario, TestEnv};

type Fr = <PsoV1 as Suite>::Field;

/// IMT depth the chain (and the full circuit) commits to.
const INCLUSION_DEPTH: usize = 32;

/// L1 settlement identity the full proof's binding commits to. The full proof
/// verifies on L1 (a different chain id + sender than the L2 mint), so these
/// are independent of the L2 submitter — any fixed values work for a proof that
/// is verified off-chain here rather than settled.
const L1_SENDER: [u8; 20] = [0x11; 20];
const L1_CHAIN_ID: u64 = 1;

pub struct S047;

#[async_trait]
impl Scenario for S047 {
    fn id(&self) -> &'static str {
        "S047"
    }
    fn description(&self) -> &'static str {
        "wallet generates a TD full proof (ownership + Merkle inclusion); proof ZK-verifies and binds both halves"
    }
    async fn run(&self, env: &TestEnv) -> eyre::Result<()> {
        run(env).await
    }
}

/// What the blocking prove+verify closure hands back to the async body: the
/// proof's public inputs + byte length (for the structural assertions) and the
/// three verifier verdicts (valid proof; both tamper attempts rejected).
struct FullProofVerdict {
    public_inputs: Vec<Vec<u8>>,
    proof_len: usize,
    verifies: bool,
    owner_tamper_rejected: bool,
    root_tamper_rejected: bool,
}

async fn run(env: &TestEnv) -> eyre::Result<()> {
    // 1. Submit a real TD (S001's happy path) and pull the committed leaf
    //    (= the chain-folded TD nft_hash) from the LeafInserted event.
    let outcome = submit_full_tribute_draft(env).await?;
    let (tree_id, leaf_index, leaf) = leaf_inserted(&outcome.receipt)?;

    // Read the TD body back so the ownership witness re-folds the SAME nft_hash
    // the chain stored as the leaf (owner + worldwide_day + currency + amount +
    // suIds). Reading from chain is the only authoritative source for the
    // aggregated amount.
    let read_provider = env.attester_zero.inner().read_provider();
    let td_view = ITributeDraft::new(TRIBUTE_DRAFT, &read_provider);
    let td_on_chain = td_view.getData(outcome.td_id).call().await?;
    let td: pso_chain_abi::entity::TributeDraft = td_on_chain.into();
    let worldwide_day =
        u64::try_from(td.worldwide_day).map_err(|_| eyre::eyre!("S047: worldwide_day overflow"))?;
    let currency =
        u16::try_from(td.currency).map_err(|_| eyre::eyre!("S047: currency overflow"))?;
    let base = u64::try_from(td.base).map_err(|_| eyre::eyre!("S047: base overflow"))?;
    let atto = u64::try_from(td.atto).map_err(|_| eyre::eyre!("S047: atto overflow"))?;

    // 2. Ownership half — the TD signs its OWN entity with the header key over
    //    the L1 binding. `su_ids` are hashed as a sorted set internally, so any
    //    order is fine.
    //
    // S001 mints the TD under a fresh random id (`outcome.td_id`), independent of
    // the header's own id. The leaf (and the circuit) fold the TD id, so bind the
    // ownership entity to the ACTUAL on-chain id — the header carries the key
    // material (`derived_owner` / `nft_sk` / `nonce`), and the id is just the
    // commitment seed, so overriding it yields exactly the minted TD's entity.
    let mut td_header = outcome.td_header.clone();
    td_header.id = outcome.td_id.to_be_bytes::<32>().to_vec();

    let wallet = pso_mobile_integration::Wallet::new(env.chain_id);
    let su_ids: Vec<Vec<u8>> = outcome
        .su_ids
        .iter()
        .map(|id| id.to_be_bytes::<32>().to_vec())
        .collect();
    let ownership = wallet
        .tribute_ownership_witness(
            td_header,
            worldwide_day,
            currency,
            base,
            atto,
            su_ids,
            L1_SENDER.to_vec(),
            L1_CHAIN_ID,
        )
        .map_err(|e| eyre::eyre!("S047: tribute_ownership_witness: {e:?}"))?;

    // The recomputed entity hash MUST equal the chain-committed leaf, and the
    // signed owner MUST equal the on-chain derivedOwner — this ties the proof's
    // ownership half to exactly what was minted.
    if ownership.nft_hash.as_slice() != leaf.as_slice() {
        return Err(eyre::eyre!(
            "S047: ownership nft_hash {:?} != committed leaf {leaf:#x} \
             (TD entity-hash drift between wallet and chain)",
            hex::encode(&ownership.nft_hash)
        ));
    }
    if ownership.derived_owner != outcome.td_owner_be {
        return Err(eyre::eyre!(
            "S047: ownership derived_owner != on-chain TD derivedOwner"
        ));
    }

    // 3. Inclusion half — place the leaf at its index in an empty depth-32 IMT
    //    (Poseidon2, the chain's tree) and take the co-path + root. The circuit
    //    re-derives the root from (leaf, index, siblings) and checks it equals
    //    `expected_merkle_root`, so this triple is inclusion-valid by construction.
    let leaf_fr = <PsoV1 as Codec>::field_from_be32(&to32(leaf.as_slice())?);
    let tree =
        Imt::<PsoV1>::new(INCLUSION_DEPTH).map_err(|e| eyre::eyre!("S047: imt::new: {e}"))?;
    let path = tree.empty_inclusion_path(leaf_index);
    let root_fr = path
        .root(leaf_fr)
        .map_err(|e| eyre::eyre!("S047: inclusion-path root: {e}"))?;
    let inclusion = pso_mobile_integration::NftInclusionWitness {
        merkle_root: PsoV1::field_to_be_bytes(&root_fr).to_vec(),
        merkle_siblings: path
            .siblings
            .iter()
            .map(|s| PsoV1::field_to_be_bytes(s).to_vec())
            .collect(),
        merkle_leaf_index: leaf_index,
    };

    // Capture the values the four public inputs must equal, before the witnesses
    // move into the blocking prover.
    let expected_owner = outcome.td_owner_be.clone();
    let expected_nft_hash = ownership.nft_hash.clone();
    let expected_binding = ownership.binding.clone();
    let expected_root = inclusion.merkle_root.clone();

    // 4 + 5. Generate the proof and verify it. barretenberg's FFI is synchronous
    // (and the prover sizes the process-global CRS), so run the whole
    // prove+verify off the async runtime on a blocking thread — as S001 does for
    // the aggregation prover.
    let verdict =
        tokio::task::spawn_blocking(move || prove_and_verify(&wallet, ownership, inclusion))
            .await
            .map_err(|e| eyre::eyre!("S047: prove/verify join: {e}"))??;

    // ---- structural assertions: the proof exists and carries both halves ----
    if verdict.proof_len == 0 {
        return Err(eyre::eyre!("S047: prove_full returned an empty proof"));
    }
    if verdict.public_inputs.len() != 4 {
        return Err(eyre::eyre!(
            "S047: expected 4 public inputs [owner, nft_hash, binding, root], got {}",
            verdict.public_inputs.len()
        ));
    }
    let expect = |idx: usize, want: &[u8], name: &str| -> eyre::Result<()> {
        if verdict.public_inputs[idx].as_slice() != want {
            return Err(eyre::eyre!(
                "S047: public input #{idx} ({name}) = {} != expected {}",
                hex::encode(&verdict.public_inputs[idx]),
                hex::encode(want)
            ));
        }
        Ok(())
    };
    // Ownership half: owner + entity hash + L1 binding.
    expect(0, &expected_owner, "owner")?;
    expect(1, &expected_nft_hash, "nft_hash")?;
    expect(2, &expected_binding, "binding")?;
    // Inclusion half: the committed Merkle root.
    expect(3, &expected_root, "expected_merkle_root")?;

    // ---- cryptographic assertions: the proof binds both halves ----
    if !verdict.verifies {
        return Err(eyre::eyre!(
            "S047: full proof failed to verify against the FullProof circuit"
        ));
    }
    if !verdict.owner_tamper_rejected {
        return Err(eyre::eyre!(
            "S047: proof still verified under a tampered `owner` — ownership not bound"
        ));
    }
    if !verdict.root_tamper_rejected {
        return Err(eyre::eyre!(
            "S047: proof still verified under a tampered `expected_merkle_root` — inclusion not bound"
        ));
    }

    tracing::info!(
        tree_id,
        leaf_index,
        proof_len = verdict.proof_len,
        su_count = outcome.su_ids.len(),
        leaf = %leaf,
        "S047: TD full proof generated and verified — binds ownership + inclusion"
    );
    Ok(())
}

/// Generate the TD full proof via the wallet FFI, then verify it with the
/// canonical `FullProof` circuit. Runs entirely on a blocking thread (caller
/// wraps it in `spawn_blocking`): every call here is a synchronous barretenberg
/// FFI hop. Returns the proof's public inputs/length plus three verdicts — the
/// honest proof verifies, and two single-field-tampered public-input sets are
/// each rejected.
fn prove_and_verify(
    wallet: &pso_mobile_integration::Wallet,
    ownership: pso_mobile_integration::NftOwnershipWitness,
    inclusion: pso_mobile_integration::NftInclusionWitness,
) -> eyre::Result<FullProofVerdict> {
    let full = wallet
        .prove_full(ownership, inclusion)
        .map_err(|e| eyre::eyre!("S047: prove_full: {e:?}"))?;
    if full.public_inputs.len() != 4 {
        return Err(eyre::eyre!(
            "S047: prove_full returned {} public inputs, expected 4",
            full.public_inputs.len()
        ));
    }

    // Reassemble the FFI's flat outputs into the typed shapes the verifier
    // expects: 32-byte BE field words → `Fr`, flat proof bytes → 32-byte words.
    let pi = |idx: usize| -> eyre::Result<Fr> {
        Ok(<PsoV1 as Codec>::field_from_be32(&to32(
            &full.public_inputs[idx],
        )?))
    };
    let public = FullPublicInputs {
        owner: pi(0)?,
        nft_hash: pi(1)?,
        binding_hash: pi(2)?,
        expected_merkle_root: pi(3)?,
    };
    let proof = Proof {
        proof: full.proof.chunks(32).map(|c| c.to_vec()).collect(),
    };

    let bb = Barretenberg::default();
    let verifies = ProofVerifier::<PsoV1, FullProof>::verify(&bb, &public, &proof)
        .map_err(|e| eyre::eyre!("S047: verify: {e}"))?;

    // Negative checks (verify-only, no re-prove): corrupt exactly one public
    // input and confirm the SAME proof no longer verifies. `nft_hash` is reused
    // as a guaranteed-canonical wrong value (it differs from both `owner` and
    // the root). `Fr` is `Copy`, so the untouched fields carry over.
    let tampered_owner = FullPublicInputs {
        owner: public.nft_hash,
        nft_hash: public.nft_hash,
        binding_hash: public.binding_hash,
        expected_merkle_root: public.expected_merkle_root,
    };
    let owner_tamper_rejected =
        !ProofVerifier::<PsoV1, FullProof>::verify(&bb, &tampered_owner, &proof)
            .map_err(|e| eyre::eyre!("S047: verify (owner tamper): {e}"))?;

    let tampered_root = FullPublicInputs {
        owner: public.owner,
        nft_hash: public.nft_hash,
        binding_hash: public.binding_hash,
        expected_merkle_root: public.nft_hash,
    };
    let root_tamper_rejected =
        !ProofVerifier::<PsoV1, FullProof>::verify(&bb, &tampered_root, &proof)
            .map_err(|e| eyre::eyre!("S047: verify (root tamper): {e}"))?;

    Ok(FullProofVerdict {
        public_inputs: full.public_inputs,
        proof_len: full.proof.len(),
        verifies,
        owner_tamper_rejected,
        root_tamper_rejected,
    })
}

/// Coerce a 32-byte slice into a fixed array (the BE field-element wire shape).
fn to32(b: &[u8]) -> eyre::Result<[u8; 32]> {
    b.try_into()
        .map_err(|_| eyre::eyre!("S047: expected 32 bytes, got {}", b.len()))
}
