//! Sample FFI — **attester** side (Mozilla UniFFI, object-oriented).
//!
//! Exposes a stateless [`Attester`] interface object holding only its on-chain
//! address; each issuance is seeded by entropy the caller passes in (so the
//! attester keeps no RNG state and needs no lock). Issuance is two steps:
//! [`Attester::generate_nft_header`] runs the consent box once to mint the
//! [`NftHeader`] (id + owner + the wallet's reconstruction material), then
//! [`Attester::issue_with_header`] assembles the on-chain [`SpendingUnit`] +
//! [`IssuanceReport`] from that header and the body fields. Splitting them lets
//! a reverted publish reissue with adjusted `sr`/`ar` without re-deriving the
//! header.
//!
//! Wires three crates: the typed entity ([`pso_chain_abi::entity`]), the
//! protocol (`pso-protocol`'s consent box + entity hashing), and the byte serde
//! from the protocol's byte helpers ([`pso_protocol::codec`]). The boundary is generated by UniFFI —
//! no `#[no_mangle]`, no manual marshalling, no hand-written header. Field
//! elements / compressed points cross as 32-byte big-endian `Vec<u8>`;
//! addresses as 20-byte `Vec<u8>`; the attester `seed` is 32 bytes of entropy.

use std::sync::Arc;

use ark_std::rand::rngs::StdRng;
use ark_std::rand::SeedableRng;
use ark_std::UniformRand;

use alloy_primitives::{Address, B256, U16, U64};
use sha2::{Digest, Sha256};

use pso_protocol::protocol::entity::Entity;
use pso_protocol::PsoV1;
use pso_protocol::Suite;

use pso_protocol::Codec;

uniffi::setup_scaffolding!();

type Fr = <PsoV1 as Suite>::Field;

/// A SpendingUnit as submitted on-chain (the FFI mirror of the `sol!` struct).
/// Field elements / addresses are big-endian `Vec<u8>`.
#[derive(Debug, uniffi::Record)]
pub struct SpendingUnit {
    /// Spending-unit id (32 bytes).
    pub su_id: Vec<u8>,
    /// `derivedOwner` commitment (32 bytes).
    pub derived_owner: Vec<u8>,
    /// Minting attester address (20 bytes).
    pub attester: Vec<u8>,
    /// Referrer address (20 bytes).
    pub referrer: Vec<u8>,
    /// Worldwide day (YYYYMMDD).
    pub worldwide_day: u32,
    /// ISO 4217 currency code.
    pub currency: u16,
    /// Amount integer part.
    pub base: u64,
    /// Amount fractional part.
    pub atto: u64,
    /// Spending-record fingerprints (each 32 bytes).
    pub spending_records: Vec<Vec<u8>>,
    /// Amendment-record fingerprints (each 32 bytes).
    pub amendment_records: Vec<Vec<u8>>,
}

/// The report an attester hands back to the wallet after issuing an NFT via the
/// consent box. All fields are 32-byte big-endian. The NFT signing key is
/// produced and destroyed inside issuance (forward secrecy); only the
/// `opaque_pk` and `nonce` (for the wallet to reconstruct its signer) and the
/// public identity (`nft_id`, `derived_owner`, `nft_hash`) leave.
#[derive(Debug, uniffi::Record)]
pub struct IssuanceReport {
    /// NFT id (random field element).
    pub nft_id: Vec<u8>,
    /// `derivedOwner = Hash(pk, nonce)` for the consent box owner.
    pub derived_owner: Vec<u8>,
    /// Entity hash of the on-chain NFT struct.
    pub nft_hash: Vec<u8>,
    /// Opaque transcript the wallet feeds back to reconstruct its signer.
    pub opaque_pk: Vec<u8>,
    /// Nonce the wallet feeds back to reconstruct its signer.
    pub nonce: Vec<u8>,
}

/// The result of issuing a SpendingUnit: the on-chain struct plus the wallet's
/// report. (UniFFI has no tuples, so the `(SpendingUnit, IssuanceReport)` pair
/// is a record.)
#[derive(Debug, uniffi::Record)]
pub struct IssuedSpendingUnit {
    /// The SpendingUnit as submitted on-chain.
    pub spending_unit: SpendingUnit,
    /// The report the wallet stores to later prove ownership.
    pub report: IssuanceReport,
}

/// The consent-box-derived part of a SpendingUnit, generated once per SU. It
/// is independent of the body (amounts, records, …), so if a publish reverts
/// the attester can re-run [`Attester::issue_with_header`] with adjusted
/// `sr`/`ar` reusing the same header — no fresh consent-box derivation, so the
/// SU keeps its `su_id` / `derived_owner` / wallet reconstruction material.
/// All fields are 32-byte big-endian.
#[derive(Debug, Clone, uniffi::Record)]
pub struct NftHeader {
    /// NFT id.
    pub nft_id: Vec<u8>,
    /// `derivedOwner` commitment.
    pub derived_owner: Vec<u8>,
    /// Opaque transcript the wallet feeds back to reconstruct its signer.
    pub opaque_pk: Vec<u8>,
    /// Nonce the wallet feeds back to reconstruct its signer.
    pub nonce: Vec<u8>,
}

/// Errors crossing the attester FFI boundary.
#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum AttesterError {
    /// An input byte buffer had the wrong length.
    #[error("bad input length: {detail}")]
    BadInput { detail: String },
    /// A consent public key failed to decode.
    #[error("invalid consent_pk: {detail}")]
    InvalidConsentPk { detail: String },
    /// Issuance (consent box / entity hashing) failed.
    #[error("issuance failed: {detail}")]
    Issuance { detail: String },
}

impl From<pso_protocol::error::Error> for AttesterError {
    fn from(e: pso_protocol::error::Error) -> Self {
        AttesterError::Issuance {
            detail: e.to_string(),
        }
    }
}

fn arr<const N: usize>(v: &[u8], what: &str) -> Result<[u8; N], AttesterError> {
    v.try_into().map_err(|_| AttesterError::BadInput {
        detail: format!("{what}: expected {N} bytes, got {}", v.len()),
    })
}

/// Seed a per-issuance RNG from caller entropy. The seed is hashed, so any
/// buffer works as long as it clears a 32-byte (256-bit) entropy floor — no
/// exact size is required.
fn issuance_rng(seed: &[u8]) -> Result<StdRng, AttesterError> {
    if seed.len() < 32 {
        return Err(AttesterError::BadInput {
            detail: format!("seed: expected >= 32 bytes of entropy, got {}", seed.len()),
        });
    }
    let mut h = Sha256::new();
    h.update(b"pso/attester/rng/v1");
    h.update(seed);
    Ok(StdRng::from_seed(h.finalize().into()))
}

/// Decode 32-byte big-endian record fingerprints into `bytes32` field elements,
/// rejecting any non-canonical value (`>=` the field modulus) **here**, naming
/// the offending record — instead of letting it surface generically from entity
/// hashing. A non-canonical fingerprint has no field element, and reducing it
/// would alias distinct byte strings onto one element.
fn fingerprints(fps: &[Vec<u8>], what: &'static str) -> Result<Vec<B256>, AttesterError> {
    fps.iter()
        .enumerate()
        .map(|(i, fp)| {
            let bytes = arr::<32>(fp, what)?;
            pso_protocol::codec::field_from_be_bytes_canonical::<Fr>(&bytes, what).map_err(|_| {
                AttesterError::BadInput {
                    detail: format!("{what} {i} is not a canonical field element (>= modulus)"),
                }
            })?;
            Ok(B256::new(bytes))
        })
        .collect()
}

/// An attester, bound to its on-chain address. Stateless: each issuance
/// is seeded by caller-supplied entropy, so there is no shared RNG to lock.
#[derive(uniffi::Object)]
pub struct Attester {
    address: [u8; 20],
}

#[uniffi::export]
impl Attester {
    /// Construct an attester from its 20-byte on-chain address.
    #[uniffi::constructor]
    pub fn new(attester_addr: Vec<u8>) -> Result<Arc<Self>, AttesterError> {
        Ok(Arc::new(Self {
            address: arr::<20>(&attester_addr, "attester_addr")?,
        }))
    }

    /// Generate the consent-box-derived [`NftHeader`] for a wallet's
    /// `consent_pk` (a 32-byte compressed point), seeded by `seed` (>= 32 bytes
    /// of caller entropy, hashed): runs the consent box (deriving the owner + the
    /// wallet's reconstruction material) and draws a fresh `nft_id`. The caller
    /// must vary `seed` per issuance, since the attester holds no RNG state —
    /// same seed yields the same SpendingUnit. The reference binding builds
    /// `seed` as 24 random bytes (drawn once per attester) ‖ an 8-byte big-endian
    /// counter incremented per call, so issues are distinct regardless of the
    /// attester implementation.
    pub fn generate_nft_header(
        &self,
        seed: Vec<u8>,
        consent_pk: Vec<u8>,
    ) -> Result<NftHeader, AttesterError> {
        let consent_pk = PsoV1::public_key_from_bytes(&arr::<32>(&consent_pk, "consent_pk")?)
            .map_err(|e| AttesterError::InvalidConsentPk {
                detail: e.to_string(),
            })?;

        // Per-issuance RNG from the caller's entropy — no shared state, no lock.
        // Consent box: derive the NFT owner for `consent_pk`; the NFT key is
        // produced and destroyed here, only `opaque_pk` + the owner seed leave.
        let mut rng = issuance_rng(&seed)?;
        let (owner_seed, opaque_pk) = PsoV1::issue_for_remote(&mut rng, &consent_pk)?;
        let owner = owner_seed.derive_owner()?;
        let nft_id = Fr::rand(&mut rng);

        Ok(NftHeader {
            nft_id: PsoV1::field_to_be_bytes(&nft_id),
            derived_owner: PsoV1::field_to_be_bytes(&owner),
            opaque_pk: PsoV1::public_key_to_bytes(&opaque_pk)?.to_vec(),
            nonce: PsoV1::field_to_be_bytes(&owner_seed.nonce),
        })
    }

    /// Assemble the full SpendingUnit + report from a previously-generated
    /// `header` and the body fields. Re-callable with adjusted `sr`/`ar`
    /// (e.g. after a reverted publish) reusing the same `header` — no consent
    /// box, no new identity. `referrer_addr` is 20 bytes; `spending_records` /
    /// `amendment_records` are record fingerprints, each a canonical field
    /// element (32-byte big-endian `Fr`) that folds into `nft_hash`.
    #[allow(clippy::too_many_arguments)]
    pub fn issue_with_header(
        &self,
        header: NftHeader,
        worldwide_day: u32,
        currency: u16,
        base: u64,
        atto: u64,
        referrer_addr: Vec<u8>,
        spending_records: Vec<Vec<u8>>,
        amendment_records: Vec<Vec<u8>>,
    ) -> Result<IssuedSpendingUnit, AttesterError> {
        let su_id = arr::<32>(&header.nft_id, "nft_id")?;
        let derived_owner = arr::<32>(&header.derived_owner, "derived_owner")?;
        let referrer = arr::<20>(&referrer_addr, "referrer_addr")?;
        let sr = fingerprints(&spending_records, "spending_record")?;
        let ar = fingerprints(&amendment_records, "amendment_record")?;

        // Build the typed entity (the on-chain SU hash preimage) directly and
        // hash it. `sr`/`ar` fold into `nft_hash`, so adjusting them re-derives
        // only the hash, not the header identity.
        let entity = pso_chain_abi::entity::SpendingUnit {
            id: B256::new(su_id),
            derived_owner: B256::new(derived_owner),
            attester: Address::from(self.address),
            referrer: Address::from(referrer),
            worldwide_day: U64::from(worldwide_day),
            currency: U16::from(currency),
            base: U64::from(base),
            atto: U64::from(atto),
            sr,
            ar,
        };
        let nft_hash = Entity::<PsoV1>::entity_hash(&entity)?;

        let spending_unit = SpendingUnit {
            su_id: header.nft_id.clone(),
            derived_owner: header.derived_owner.clone(),
            attester: self.address.to_vec(),
            referrer: referrer.to_vec(),
            worldwide_day,
            currency,
            base,
            atto,
            spending_records,
            amendment_records,
        };
        let report = IssuanceReport {
            nft_id: header.nft_id,
            derived_owner: header.derived_owner,
            nft_hash: PsoV1::field_to_be_bytes(&nft_hash),
            opaque_pk: header.opaque_pk,
            nonce: header.nonce,
        };
        Ok(IssuedSpendingUnit {
            spending_unit,
            report,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use pso_protocol::Codec;

    /// A valid consent public key — `sk·G` (compressed Grumpkin point) for a
    /// small fixed secret. `generate_nft_header` validates it via
    /// `public_key_from_bytes`, so it must be a real on-curve point.
    fn valid_consent_pk() -> Vec<u8> {
        let mut sk_bytes = [0u8; 32];
        sk_bytes[0] = 7; // canonical, non-zero little-endian scalar
        let sk = PsoV1::secret_from_bytes(&sk_bytes).expect("secret");
        PsoV1::public_key_to_bytes(&PsoV1::public_key_from_secret(&sk))
            .expect("pk bytes")
            .to_vec()
    }

    fn seed(tag: u8) -> Vec<u8> {
        vec![tag; 32]
    }

    /// A canonical field-element fingerprint (small ⇒ < modulus).
    fn fp(tag: u8) -> Vec<u8> {
        let mut b = [0u8; 32];
        b[31] = tag;
        b.to_vec()
    }

    #[test]
    fn new_validates_address_length() {
        assert!(Attester::new(vec![0xab; 20]).is_ok());
        assert!(matches!(
            Attester::new(vec![0u8; 19]),
            Err(AttesterError::BadInput { .. })
        ));
    }

    #[test]
    fn generate_nft_header_rejects_bad_consent_pk() {
        let att = Attester::new(vec![0xab; 20]).unwrap();
        // Wrong length.
        assert!(matches!(
            att.generate_nft_header(seed(1), vec![0u8; 31]),
            Err(AttesterError::BadInput { .. })
        ));
        // Right length but not a valid point.
        assert!(matches!(
            att.generate_nft_header(seed(1), vec![0xff; 32]),
            Err(AttesterError::InvalidConsentPk { .. })
        ));
    }

    #[test]
    fn generate_nft_header_rejects_seed_below_floor() {
        let att = Attester::new(vec![0xab; 20]).unwrap();
        assert!(matches!(
            att.generate_nft_header(vec![0u8; 31], valid_consent_pk()),
            Err(AttesterError::BadInput { .. })
        ));
    }

    #[test]
    fn generate_nft_header_is_deterministic_per_seed() {
        let att = Attester::new(vec![0xab; 20]).unwrap();
        let pk = valid_consent_pk();
        let h1 = att.generate_nft_header(seed(9), pk.clone()).unwrap();
        let h2 = att.generate_nft_header(seed(9), pk.clone()).unwrap();
        assert_eq!(h1.nft_id, h2.nft_id);
        assert_eq!(h1.derived_owner, h2.derived_owner);
        assert_eq!(h1.derived_owner.len(), 32);
        // A different seed yields a distinct identity.
        let h3 = att.generate_nft_header(seed(10), pk).unwrap();
        assert_ne!(h1.nft_id, h3.nft_id);
    }

    #[test]
    fn issue_round_trip_and_reissue_reuses_identity() {
        let att = Attester::new(vec![0xab; 20]).unwrap();
        let header = att.generate_nft_header(seed(3), valid_consent_pk()).unwrap();

        let issued = att
            .issue_with_header(
                header.clone(),
                20_250_101,
                978,
                100,
                0,
                vec![0u8; 20],
                vec![fp(1), fp(2)],
                vec![fp(3)],
            )
            .unwrap();

        // The on-chain SU mirrors the inputs + the header identity.
        assert_eq!(issued.spending_unit.su_id, header.nft_id);
        assert_eq!(issued.spending_unit.derived_owner, header.derived_owner);
        assert_eq!(issued.spending_unit.attester, vec![0xab; 20]);
        assert_eq!(issued.spending_unit.currency, 978);
        assert_eq!(issued.report.derived_owner, header.derived_owner);
        assert_eq!(issued.report.nft_hash.len(), 32);
        assert!(issued.report.nft_hash.iter().any(|b| *b != 0));

        // Re-issue with the SAME header but different records: identity
        // (su_id / derived_owner) is preserved, nft_hash changes (sr/ar fold in).
        let reissued = att
            .issue_with_header(
                header,
                20_250_101,
                978,
                100,
                0,
                vec![0u8; 20],
                vec![fp(4)],
                vec![],
            )
            .unwrap();
        assert_eq!(reissued.spending_unit.su_id, issued.spending_unit.su_id);
        assert_eq!(reissued.report.derived_owner, issued.report.derived_owner);
        assert_ne!(reissued.report.nft_hash, issued.report.nft_hash);
    }

    #[test]
    fn issue_rejects_non_canonical_fingerprint() {
        let att = Attester::new(vec![0xab; 20]).unwrap();
        let header = att.generate_nft_header(seed(5), valid_consent_pk()).unwrap();
        // 0xff..ff >= field modulus.
        assert!(matches!(
            att.issue_with_header(
                header,
                20_250_101,
                978,
                100,
                0,
                vec![0u8; 20],
                vec![vec![0xff; 32]],
                vec![],
            ),
            Err(AttesterError::BadInput { .. })
        ));
    }

    /// Emits a valid consent_pk hex — the input vector the Kotlin functional
    /// test pins. Run with `--ignored --nocapture` to refresh it.
    #[test]
    #[ignore]
    fn print_consent_pk_vector() {
        println!("consent_pk_hex={}", hex_encode(&valid_consent_pk()));
    }

    fn hex_encode(b: &[u8]) -> String {
        b.iter().map(|x| format!("{x:02x}")).collect()
    }
}
